github: improve auto-build message and usage

diff --git a/qubesbuilder/plugins/github/scripts/auto-build b/qubesbuilder/plugins/github/scripts/auto-build
--- a/qubesbuilder/plugins/github/scripts/auto-build
+++ b/qubesbuilder/plugins/github/scripts/auto-build
@@ -19,10 +19,10 @@ if [ "$DEBUG" == 1 ]; then
 fi
 
 usage() {
-    echo "Usage: $0 component-name" >&2
+    echo "Usage: $0 builder-dir component-name" >&2
 }
 
-if [ -z "$1" ]; then
+if [ $# -lt 2 ]; then
     usage
     exit 1
 fi
@@ -34,11 +34,14 @@ set -e
 BUILDER_DIR="$1"
 shift 1
 
-cd "$BUILDER_DIR"
+cd "$BUILDER_DIR" || {
+    echo "ERROR: Invalid builder directory."
+    exit 1
+}
 
 # Sanity checks
 if [ "${1##*/}" != "${1}" ]; then
-    echo "Found '/' in argument" >&2
+    echo "ERROR: Found '/' in argument." >&2
     exit 1
 fi
 
@@ -49,7 +52,7 @@ for c in $(./qb config get-var components); do
     fi
 done
 if [ -z "$found" ]; then
-    echo "No such component: $1" >&2
+    echo "ERROR: No such component '$1'." >&2
     exit 1
 fi
 
@@ -127,6 +130,7 @@ rm -f "$log_service_output_file"
 
 if [ -z "$built_for_host" ] && [ -z "$built_for_vm" ]; then
     # nothing was built, something gone wrong
+    echo "WARNING: Nothing was built, something gone wrong or version tag was not found."
     exit 1
 fi
 
