get-and-verify-source: several fixes
From @DemiMarie's suggestions.

diff --git a/qubesbuilder/plugins/fetch/scripts/get-and-verify-source b/qubesbuilder/plugins/fetch/scripts/get-and-verify-source
--- a/qubesbuilder/plugins/fetch/scripts/get-and-verify-source
+++ b/qubesbuilder/plugins/fetch/scripts/get-and-verify-source
@@ -172,10 +172,10 @@ while [[ $# -gt 0 ]]; do
     shift
 done
 
-# Sanity check on provided maintainers
+# Validity check on provided maintainers
 for maint in "${MAINTAINERS[@]}"; do
     if ! [[ "$maint" =~ ^[a-fA-F0-9]{40}$ ]]; then
-        echo "Invalid maintainer provided: $maint"
+        printf 'Invalid maintainer provided: %q\n' "$maint"
         exit 1
     fi
 done
@@ -189,7 +189,7 @@ elif ! [[ "${LESS_SECURE_SIGNED_COMMITS_SUFFICIENT=}" =~ ^[A-Za-z0-9$'\x20\n'-]*
 fi
 
 # Ensure to have COMPONENT set
-[ -z "$COMPONENT" ] && {
+[[ -n "$COMPONENT" ]] || {
     echo "ERROR: COMPONENT is not set!" >&2
     exit 1
 }
@@ -223,16 +223,23 @@ fi
 [ -n "${GIT_REMOTE=}" ] && GIT_URL=$GIT_REMOTE
 
 # Default values
-: "${IGNORE_MISSING=0}"
-: "${GIT_CLONE_FAST=0}"
+case ${IGNORE_MISSING=0} in
+(0|1) :;;
+(*) printf 'Invalid IGNORE_MISSING (must be 0 or 1): %q\n' "$IGNORE_MISSING" >&2; exit 1;;
+esac
 
-# Define common GIT options
-GIT_OPTIONS=
-if [ "$GIT_CLONE_FAST" = "1" ]; then
-    GIT_OPTIONS+="--depth=1"
+case ${GIT_CLONE_FAST=0} in
+(0|1) :;;
+(*) printf 'Invalid GIT_CLONE_FAST (must be 0 or 1): %q\n' "$GIT_CLONE_FAST" >&2; exit 1;;
+esac
+
+# Define common Git options
+GIT_OPTIONS=()
+if [[ "$GIT_CLONE_FAST" = "1" ]]; then
+    GIT_OPTIONS+=("--depth=1")
 fi
 
-GIT_MERGE_OPTS="--ff-only"
+GIT_MERGE_OPTS=("--ff-only")
 
 # Sanity check on BRANCH and REPO
 if ! [[ "$BRANCH" =~ ^[A-Za-z][A-Za-z0-9._-]+$ ]]; then
@@ -255,8 +262,9 @@ if [[ "$CLEAN" = '1' ]]; then
 fi
 if [[ -d "$REPO" ]]; then
     cd "$REPO"
-    if [ "$GIT_CLONE_FAST" != "1" ] && [ "$(git rev-parse --is-shallow-repository)" == "true" ]; then
-        GIT_OPTIONS+="--unshallow"
+    is_shallow=$(git rev-parse --is-shallow-repository)
+    if [[ "$GIT_CLONE_FAST" -ne "1" ]] && [[ "$is_shallow" = "true" ]]; then
+        GIT_OPTIONS+=("--unshallow")
     fi
     print_headers
     if [ "$DO_MERGE" == "1" ]; then
@@ -267,7 +275,7 @@ if [[ -d "$REPO" ]]; then
         fi
         VERIFY_REF="$rev"
     else
-        if ! git fetch $GIT_OPTIONS -q --tags -- "$GIT_URL" "$BRANCH"; then
+        if ! git fetch "${GIT_OPTIONS[@]}" -q --tags -- "$GIT_URL" "$BRANCH"; then
             if [ "$IGNORE_MISSING" = "1" ]; then exit 0; else exit 1; fi
         fi
         VERIFY_REF=FETCH_HEAD
@@ -278,7 +286,7 @@ if [[ -d "$REPO" ]]; then
 else
     rm -f -- "$REPO"
     print_headers
-    if ! git clone $GIT_OPTIONS -n -q -b "$BRANCH" "$GIT_URL" "$REPO"; then
+    if ! git clone "${GIT_OPTIONS[@]}" -n -q -b "$BRANCH" "$GIT_URL" "$REPO"; then
         if [ "$IGNORE_MISSING" == "1" ]; then exit 0; else exit 1; fi
     fi
     VERIFY_REF=HEAD fresh_clone=:
@@ -417,10 +425,10 @@ fi
 if ! "$fresh_clone"; then
     if [ "$DO_MERGE" = "1" ]; then
         echo "Merging FETCH_HEAD into $REPO"
-        git -c merge.verifySignatures=false merge $GIT_MERGE_OPTS --no-edit "$VERIFY_REF"
+        git -c merge.verifySignatures=false merge "${GIT_MERGE_OPTS[@]}" --no-edit "$VERIFY_REF"
     else
         echo "--> Merging..."
-        git -c merge.verifySignatures=no merge $GIT_MERGE_OPTS --commit -q "$VERIFY_REF"
+        git -c merge.verifySignatures=no merge "${GIT_MERGE_OPTS[@]}" --commit -q "$VERIFY_REF"
         tracking_branch="refs/remotes/$GIT_REMOTE/$BRANCH"
         if [ -f ".git/$tracking_branch" ]; then
             git update-ref -- "$tracking_branch" "$VERIFY_REF"
